### ISSUE TITLE
为什么不用 Looper 呢？

### ISSUE THREAD

**Issue by codetalks-new** [liaohuqiu/android-ActionQueue#3]
RT： 这机制跟 Looper的一样吗？ 而且 Looper 提供的功能更多。
另： 如果增加 Action Dependency 这样 的功能就有区分了。

**Comment by liaohuqiu** [comment]
There is a big difference between this feature and Looper: the action in message loop will be executed in a specify time(Sometime at once) when UI thread is not busy. What's more, the action in loop can not take too much work, neither too much time. And this `ActionQueue` allows us to do these.

**Comment by codetalks-new** [comment]
你说是有些道理，但我仔细想了一下，再看了眼源代码。得到以下几个看法，您看怎么样？
1) Looper 不仅仅是可以绑定在 UI 线程的。如果你绑定在其他Worker thread 也可以做一些耗时的工作，不 blocking UI Thread。
2） 如果 ActionQueue 绑定在 UI 线程了，也不应该在其中做一些耗时的工作，或者 UI 线程在忙，应该让它先忙完。
3）让 Action 实现 Runable 接口，把 onAction 抽象方法去掉，岂不是更好呢？
